services:
  server:
    build: ./server
    tty: true
    ports:
      - "5001:5001"

  client:
    build: ./client
    tty: true
    ports:
      - "4173:4173"

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: mea_db
    volumes:
      - ./data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_pass
    command: server /data --console-address ":9001"

volumes:
  minio_data:
