services:
  server:
    build: ./server
    tty: true
    ports:
      - "5001:5001"

  client:
    build: ./client
    tty: true
    ports:
      - "4173:4173"

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: mea_db
    volumes:
      - ./data:/var/lib/mysql
