services:
  server:
    build: ./server
    tty: true
    ports:
      - "5001:5001"
    depends_on:
      - minio
      - mysql
    environment:
      - FLASK_ENV=docker

  backend:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=mea_db
      - MYSQL_ROOT_PASSWORD=root_pass
      - MINIO_HOST=minio
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_pass

  client:
    build: ./client
    tty: true
    ports:
      - "4173:4173"

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: mea_db
    volumes:
      - ./data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_pass
    command: server /data --console-address ":9001" --compat

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_pass;
        /usr/bin/mc mb myminio/plot-figure || true;
        /usr/bin/mc anonymous set download myminio/plot-figure;
        while true; do sleep 3600; done;
      "
