spring:
  application:
    name: figure-management
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:mea_db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root_pass}
  flyway:
    baseline-on-migrate: true
  jooq:
    sql-dialect: MYSQL
#
#  cors:
#    allowed-origins:
#      - http://localhost:5173
#      - http://localhost:4173
#      - https://mea-viewer.vercel.app

minio:
  endpoint: http://${MINIO_HOST:localhost}:9000
  access-key: ${MINIO_ROOT_USER:minio_admin}
  secret-key: ${MINIO_ROOT_PASSWORD:minio_pass}

logging:
  level:
    root: INFO
    org.jooq.tools.LoggerListener: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

