FROM python:3.12

WORKDIR /usr/src/server

COPY . .

RUN pip install --upgrade pip \
 && pip install -r requirements.txt
#  && pip install git+https://github.com/kkito0726/MEA_modules.git


CMD ["gunicorn", "--bind", "0.0.0.0:5001", "--timeout", "10800", "app:app"]